local beast = require("beast")

local create_rom = beast.rom.create_rom
local read_rom = beast.rom.read_rom
local create_instruction = beast.rom.create_instruction

local op = beast.rom.operands

local create_processor_register_operand = beast.rom.create_processor_register_operand
local create_dynamic_byte_operand = beast.rom.create_dynamic_byte_operand
local create_dynamic_octet_operand = beast.rom.create_dynamic_octet_operand

describe("Rom", function()
   it("reads a bank", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/ret.gb", "rb"))
      assert.truthy(rom.nbanks == 1)
   end)

   it("reads a bank byte", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/ret.gb", "rb"))
      assert.truthy(rom.banks[0].size == 1)
   end)

   it("reads ret instruction", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/ret.gb", "rb"))
      assert.are.same(rom.banks[0].instructions, {
         create_instruction("ret")
      })
   end)

   it("reads basic instructions", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/basic_instructions.gb", "rb"))
      assert.are.same(rom.banks[0].instructions, {
            create_instruction("nop"),
            create_instruction("halt"),
            create_instruction("di"),
            create_instruction("ei"),
            create_instruction("ld", op.a_register, op.a_register),
            create_instruction("ld", op.a_register, op.b_register),
            create_instruction("ld", op.a_register, op.c_register),
            create_instruction("ld", op.a_register, op.d_register),
            create_instruction("ld", op.a_register, op.e_register),
            create_instruction("ld", op.a_register, op.f_register),
            create_instruction("ld", op.a_register, op.l_register),
            create_instruction("ld", op.b_register, op.a_register),
            create_instruction("ld", op.b_register, op.b_register),
            create_instruction("ld", op.b_register, op.c_register),
            create_instruction("ld", op.b_register, op.d_register),
            create_instruction("ld", op.b_register, op.e_register),
            create_instruction("ld", op.b_register, op.h_register),
            create_instruction("ld", op.b_register, op.l_register),
            create_instruction("ld", op.c_register, op.a_register),
            create_instruction("ld", op.c_register, op.b_register),
            create_instruction("ld", op.c_register, op.c_register),
            create_instruction("ld", op.c_register, op.d_register),
            create_instruction("ld", op.c_register, op.e_register),
            create_instruction("ld", op.c_register, op.h_register),
            create_instruction("ld", op.c_register, op.l_register),
            create_instruction("ld", op.d_register, op.a_register),
            create_instruction("ld", op.d_register, op.b_register),
            create_instruction("ld", op.d_register, op.c_register),
            create_instruction("ld", op.d_register, op.d_register),
            create_instruction("ld", op.d_register, op.e_register),
            create_instruction("ld", op.d_register, op.h_register),
            create_instruction("ld", op.d_register, op.l_register),
            create_instruction("ld", op.e_register, op.a_register),
            create_instruction("ld", op.e_register, op.b_register),
            create_instruction("ld", op.e_register, op.c_register),
            create_instruction("ld", op.e_register, op.d_register),
            create_instruction("ld", op.e_register, op.e_register),
            create_instruction("ld", op.e_register, op.h_register),
            create_instruction("ld", op.e_register, op.l_register),
            create_instruction("ld", op.h_register, op.a_register),
            create_instruction("ld", op.h_register, op.b_register),
            create_instruction("ld", op.h_register, op.c_register),
            create_instruction("ld", op.h_register, op.d_register),
            create_instruction("ld", op.h_register, op.e_register),
            create_instruction("ld", op.h_register, op.h_register),
            create_instruction("ld", op.h_register, op.l_register),
            create_instruction("ld", op.l_register, op.a_register),
            create_instruction("ld", op.l_register, op.b_register),
            create_instruction("ld", op.l_register, op.c_register),
            create_instruction("ld", op.l_register, op.d_register),
            create_instruction("ld", op.l_register, op.e_register),
            create_instruction("ld", op.l_register, op.h_register),
            create_instruction("ld", op.l_register, op.l_register),
            create_instruction("ld", op.a_register, op.hl_register_set_reference),
            create_instruction("ld", op.b_register, op.hl_register_set_reference),
            create_instruction("ld", op.c_register, op.hl_register_set_reference),
            create_instruction("ld", op.d_register, op.hl_register_set_reference),
            create_instruction("ld", op.e_register, op.hl_register_set_reference),
            create_instruction("ld", op.h_register, op.hl_register_set_reference),
            create_instruction("ld", op.l_register, op.hl_register_set_reference),
            create_instruction("ld", op.hl_register_set_reference, op.a_register),
            create_instruction("ld", op.hl_register_set_reference, op.b_register),
            create_instruction("ld", op.hl_register_set_reference, op.c_register),
            create_instruction("ld", op.hl_register_set_reference, op.d_register),
            create_instruction("ld", op.hl_register_set_reference, op.e_register),
            create_instruction("ld", op.hl_register_set_reference, op.h_register),
            create_instruction("ld", op.hl_register_set_reference, op.l_register),
            create_instruction("ld", op.a_register, op.c_register_reference),
            create_instruction("ld", op.c_register_reference, op.a_register),
            create_instruction("ld", op.a_register, op.hl_inc_register_set_reference),
            create_instruction("ld", op.a_register, op.hl_dec_register_set_reference),
            create_instruction("ld", op.a_register, op.bc_register_set_reference),
            create_instruction("ld", op.a_register, op.de_register_set_reference),
            create_instruction("ld", op.hl_inc_register_set_reference, op.a_register),
            create_instruction("ld", op.hl_dec_register_set_reference, op.a_register),
            create_instruction("ld", op.bc_register_set_reference, op.a_register),
            create_instruction("ld", op.de_register_set_reference, op.a_register),
            create_instruction("add", op.a_register, op.a_register),
            create_instruction("add", op.a_register, op.b_register),
            create_instruction("add", op.a_register, op.c_register),
            create_instruction("add", op.a_register, op.d_register),
            create_instruction("add", op.a_register, op.e_register),
            create_instruction("add", op.a_register, op.h_register),
            create_instruction("add", op.a_register, op.l_register),
            create_instruction("add", op.a_register, op.hl_register_set_reference),
            create_instruction("adc", op.a_register, op.a_register),
            create_instruction("adc", op.a_register, op.b_register),
            create_instruction("adc", op.a_register, op.c_register),
            create_instruction("adc", op.a_register, op.d_register),
            create_instruction("adc", op.a_register, op.e_register),
            create_instruction("adc", op.a_register, op.h_register),
            create_instruction("adc", op.a_register, op.l_register),
            create_instruction("adc", op.a_register, op.hl_register_set_reference),
            create_instruction("sub", op.a_register, op.a_register),
            create_instruction("sub", op.a_register, op.b_register),
            create_instruction("sub", op.a_register, op.c_register),
            create_instruction("sub", op.a_register, op.d_register),
            create_instruction("sub", op.a_register, op.e_register),
            create_instruction("sub", op.a_register, op.h_register),
            create_instruction("sub", op.a_register, op.l_register),
            create_instruction("sub", op.a_register, op.hl_register_set_reference),
            create_instruction("sbc", op.a_register, op.a_register),
            create_instruction("sbc", op.a_register, op.b_register),
            create_instruction("sbc", op.a_register, op.c_register),
            create_instruction("sbc", op.a_register, op.d_register),
            create_instruction("sbc", op.a_register, op.e_register),
            create_instruction("sbc", op.a_register, op.h_register),
            create_instruction("sbc", op.a_register, op.l_register),
            create_instruction("sbc", op.a_register, op.hl_register_set_reference),
            create_instruction("sbc", op.hl_register_set, op.hl_register_set),
            create_instruction("sbc", op.hl_register_set, op.bc_register_set),
            create_instruction("sbc", op.hl_register_set, op.de_register_set),
            create_instruction("daa"),
            create_instruction("scf"),
            create_instruction("and", op.a_register, op.a_register),
            create_instruction("and", op.a_register, op.b_register),
            create_instruction("and", op.a_register, op.c_register),
            create_instruction("and", op.a_register, op.d_register),
            create_instruction("and", op.a_register, op.e_register),
            create_instruction("and", op.a_register, op.h_register),
            create_instruction("and", op.a_register, op.l_register),
            create_instruction("and", op.a_register, op.hl_register_set_reference),
            create_instruction("xor", op.a_register, op.a_register),
            create_instruction("xor", op.a_register, op.b_register),
            create_instruction("xor", op.a_register, op.c_register),
            create_instruction("xor", op.a_register, op.d_register),
            create_instruction("xor", op.a_register, op.e_register),
            create_instruction("xor", op.a_register, op.h_register),
            create_instruction("xor", op.a_register, op.l_register),
            create_instruction("xor", op.a_register, op.hl_register_set_reference),
            create_instruction("or", op.a_register, op.a_register),
            create_instruction("or", op.a_register, op.b_register),
            create_instruction("or", op.a_register, op.c_register),
            create_instruction("or", op.a_register, op.d_register),
            create_instruction("or", op.a_register, op.e_register),
            create_instruction("or", op.a_register, op.h_register),
            create_instruction("or", op.a_register, op.l_register),
            create_instruction("or", op.a_register, op.hl_register_set_reference),
            create_instruction("cp", op.a_register, op.a_register),
            create_instruction("cp", op.a_register, op.b_register),
            create_instruction("cp", op.a_register, op.c_register),
            create_instruction("cp", op.a_register, op.d_register),
            create_instruction("cp", op.a_register, op.e_register),
            create_instruction("cp", op.a_register, op.h_register),
            create_instruction("cp", op.a_register, op.l_register),
            create_instruction("cp", op.a_register, op.hl_register_set_reference),
            create_instruction("cpl"),
            create_instruction("ccf"),
            create_instruction("rlca"),
            create_instruction("rla"),
            create_instruction("rrca"),
            create_instruction("rra"),
            create_instruction("inc", op.a_register),
            create_instruction("inc", op.b_register),
            create_instruction("inc", op.c_register),
            create_instruction("inc", op.d_register),
            create_instruction("inc", op.e_register),
            create_instruction("inc", op.h_register),
            create_instruction("inc", op.l_register),
            create_instruction("inc", op.hl_register_set),
            create_instruction("inc", op.bc_register_set),
            create_instruction("inc", op.de_register_set),
            create_instruction("inc", op.hl_register_set_reference),
            create_instruction("dec", op.a_register),
            create_instruction("dec", op.b_register),
            create_instruction("dec", op.c_register),
            create_instruction("dec", op.d_register),
            create_instruction("dec", op.e_register),
            create_instruction("dec", op.h_register),
            create_instruction("dec", op.l_register),
            create_instruction("dec", op.hl_register_set),
            create_instruction("dec", op.bc_register_set),
            create_instruction("dec", op.de_register_set),
            create_instruction("dec", op.hl_register_set_reference),
            create_instruction("push", op.af_register_set),
            create_instruction("push", op.bc_register_set),
            create_instruction("push", op.de_register_set),
            create_instruction("push", op.hl_register_set),
            create_instruction("pop", op.af_register_set),
            create_instruction("pop", op.bc_register_set),
            create_instruction("pop", op.de_register_set),
            create_instruction("pop", op.hl_register_set),
            create_instruction("inc", op.sp_register),
            create_instruction("dec", op.sp_register),
            create_instruction("ld", op.sp_register, op.hl_register_set),
            create_instruction("add", op.hl_register_set, op.sp_register),
            create_instruction("jp", op.hl_register_set_reference),
            create_instruction("rst", op.vector_00h),
            create_instruction("rst", op.vector_08h),
            create_instruction("rst", op.vector_10h),
            create_instruction("rst", op.vector_18h),
            create_instruction("rst", op.vector_20h),
            create_instruction("rst", op.vector_28h),
            create_instruction("rst", op.vector_30h),
            create_instruction("rst", op.vector_38h),
            create_instruction("ret"),
            create_instruction("reti"),
            create_instruction("ret", op.c_condition),
            create_instruction("ret", op.z_condition),
            create_instruction("ret", op.nc_condition),
            create_instruction("ret", op.nz_condition)
      })
   end)

   it("reads instructions with a dynamic byte operand", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/byte_op_instructions.gb", "rb"))
      assert.are.same(rom.banks[0].instructions, {
         create_instruction("ld", op.a_register, create_dynamic_byte_operand(0x00), 2),
         create_instruction("ld", op.b_register, create_dynamic_byte_operand(0x10), 2),
         create_instruction("ld", op.c_register, create_dynamic_byte_operand(0x20), 2),
         create_instruction("ld", op.d_register, create_dynamic_byte_operand(0x30), 2),
         create_instruction("ld", op.e_register, create_dynamic_byte_operand(0x40), 2),
         create_instruction("ld", op.h_register, create_dynamic_byte_operand(0x50), 2),
         create_instruction("ld", op.l_register, create_dynamic_byte_operand(0x60), 2),
         -- TODO: these ldio instructions should be by reference
         create_instruction("ldio", op.a_register, create_dynamic_byte_operand(0x70, false), 2),
         create_instruction("ldio", create_dynamic_byte_operand(0x80, false), op.a_register, 2),
         create_instruction("ld", op.hl_register_set_reference, create_dynamic_byte_operand(0x90), 2),
         create_instruction("add", op.a_register, create_dynamic_byte_operand(0xa0), 2),
         create_instruction("adc", op.a_register, create_dynamic_byte_operand(0xb0), 2),
         create_instruction("sub", op.a_register, create_dynamic_byte_operand(0xc0), 2),
         create_instruction("sbc", op.a_register, create_dynamic_byte_operand(0xd0), 2),
         create_instruction("and", op.a_register, create_dynamic_byte_operand(0xe0), 2),
         create_instruction("xor", op.a_register, create_dynamic_byte_operand(0xf0), 2),
         create_instruction("or", op.a_register, create_dynamic_byte_operand(0x01), 2),
         create_instruction("cp", op.a_register, create_dynamic_byte_operand(0x11), 2),
         create_instruction("add", op.sp_register, create_dynamic_byte_operand(0x21), 2),
         create_instruction("ld", op.hl_register_set, create_processor_register_operand("sp", false, false, 0x31), 2),
         -- TODO: these bytes should actually be negative and relative
         create_instruction("jr", create_dynamic_byte_operand(0xfe), nil, 2),
         create_instruction("jr", op.c_condition, create_dynamic_byte_operand(0xfc), 2),
         create_instruction("jr", op.z_condition, create_dynamic_byte_operand(0xfa), 2),
         create_instruction("jr", op.nc_condition, create_dynamic_byte_operand(0xf8), 2),
         create_instruction("jr", op.nz_condition, create_dynamic_byte_operand(0xf6), 2)
      })
   end)

   it("reads instructions with a dynamic octet operand", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/octet_op_instructions.gb", "rb"))
      assert.are.same(rom.banks[0].instructions, {
         -- TODO: these next two instructions are supposed to have reference addresses
         create_instruction("ld", op.a_register, create_dynamic_octet_operand(0x0000), 3),
         create_instruction("ld", create_dynamic_octet_operand(0x0100), op.a_register, 3),
         create_instruction("ld", op.hl_register_set, create_dynamic_octet_operand(0x0200), 3),
         create_instruction("ld", op.bc_register_set, create_dynamic_octet_operand(0x0300), 3),
         create_instruction("ld", op.de_register_set, create_dynamic_octet_operand(0x0400), 3),
         create_instruction("ld", op.sp_register, create_dynamic_octet_operand(0x0500), 3),
         -- TODO: this instruction is supposed to have a reference addresse
         create_instruction("ld", create_dynamic_octet_operand(0x0600), op.sp_register, 3),
         create_instruction("call", create_dynamic_octet_operand(0x0700), nil, 3),
         create_instruction("call", op.c_condition, create_dynamic_octet_operand(0x0800), 3),
         create_instruction("call", op.z_condition, create_dynamic_octet_operand(0x0900), 3),
         create_instruction("call", op.nc_condition, create_dynamic_octet_operand(0x0a00), 3),
         create_instruction("call", op.nz_condition, create_dynamic_octet_operand(0x0b00), 3),
         create_instruction("jp", create_dynamic_octet_operand(0x0c00), nil, 3),
         create_instruction("jp", op.c_condition, create_dynamic_octet_operand(0x0f00), 3),
         create_instruction("jp", op.z_condition, create_dynamic_octet_operand(0x1000), 3),
         create_instruction("jp", op.nc_condition, create_dynamic_octet_operand(0x1100), 3),
         create_instruction("jp", op.nz_condition, create_dynamic_octet_operand(0x1200), 3)
      })
   end)

   it("reads extended instructions", function()
      local rom = create_rom()
      read_rom(rom, io.open("./spec/fixtures/extended_instructions.gb", "rb"))
      assert.are.same(rom.banks[0].instructions, {
         create_instruction("stop", create_dynamic_byte_operand(0), nil, 2),
         create_instruction("rlc", op.a_register, nil, 2),
         create_instruction("rlc", op.b_register, nil, 2),
         create_instruction("rlc", op.c_register, nil, 2),
         create_instruction("rlc", op.d_register, nil, 2),
         create_instruction("rlc", op.e_register, nil, 2),
         create_instruction("rlc", op.h_register, nil, 2),
         create_instruction("rlc", op.l_register, nil, 2),
         create_instruction("rlc", op.hl_register_set_reference, nil, 2),
         create_instruction("rrc", op.a_register, nil, 2),
         create_instruction("rrc", op.b_register, nil, 2),
         create_instruction("rrc", op.c_register, nil, 2),
         create_instruction("rrc", op.d_register, nil, 2),
         create_instruction("rrc", op.e_register, nil, 2),
         create_instruction("rrc", op.h_register, nil, 2),
         create_instruction("rrc", op.l_register, nil, 2),
         create_instruction("rrc", op.hl_register_set_reference, nil, 2),
         create_instruction("rl", op.a_register, nil, 2),
         create_instruction("rl", op.b_register, nil, 2),
         create_instruction("rl", op.c_register, nil, 2),
         create_instruction("rl", op.d_register, nil, 2),
         create_instruction("rl", op.e_register, nil, 2),
         create_instruction("rl", op.h_register, nil, 2),
         create_instruction("rl", op.l_register, nil, 2),
         create_instruction("rl", op.hl_register_set_reference, nil, 2),
         create_instruction("rr", op.a_register, nil, 2),
         create_instruction("rr", op.b_register, nil, 2),
         create_instruction("rr", op.c_register, nil, 2),
         create_instruction("rr", op.d_register, nil, 2),
         create_instruction("rr", op.e_register, nil, 2),
         create_instruction("rr", op.h_register, nil, 2),
         create_instruction("rr", op.l_register, nil, 2),
         create_instruction("rr", op.hl_register_set_reference, nil, 2),
         create_instruction("sla", op.a_register, nil, 2),
         create_instruction("sla", op.b_register, nil, 2),
         create_instruction("sla", op.c_register, nil, 2),
         create_instruction("sla", op.d_register, nil, 2),
         create_instruction("sla", op.e_register, nil, 2),
         create_instruction("sla", op.h_register, nil, 2),
         create_instruction("sla", op.l_register, nil, 2),
         create_instruction("sla", op.hl_register_set_reference, nil, 2),
         create_instruction("sra", op.a_register, nil, 2),
         create_instruction("sra", op.b_register, nil, 2),
         create_instruction("sra", op.c_register, nil, 2),
         create_instruction("sra", op.d_register, nil, 2),
         create_instruction("sra", op.e_register, nil, 2),
         create_instruction("sra", op.h_register, nil, 2),
         create_instruction("sra", op.l_register, nil, 2),
         create_instruction("sra", op.hl_register_set_reference, nil, 2),
         create_instruction("swap", op.a_register, nil, 2),
         create_instruction("swap", op.b_register, nil, 2),
         create_instruction("swap", op.c_register, nil, 2),
         create_instruction("swap", op.d_register, nil, 2),
         create_instruction("swap", op.e_register, nil, 2),
         create_instruction("swap", op.h_register, nil, 2),
         create_instruction("swap", op.l_register, nil, 2),
         create_instruction("swap", op.hl_register_set_reference, nil, 2),
         create_instruction("srl", op.a_register, nil, 2),
         create_instruction("srl", op.b_register, nil, 2),
         create_instruction("srl", op.c_register, nil, 2),
         create_instruction("srl", op.d_register, nil, 2),
         create_instruction("srl", op.e_register, nil, 2),
         create_instruction("srl", op.h_register, nil, 2),
         create_instruction("srl", op.l_register, nil, 2),
         create_instruction("srl", op.hl_register_set_reference, nil, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(0), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(1), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(2), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(3), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(4), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(5), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(6), op.hl_register_set_reference, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.a_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.b_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.c_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.d_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.e_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.h_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.l_register, 2),
         create_instruction("bit", create_dynamic_byte_operand(7), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(0), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(1), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(2), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(3), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(4), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(5), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(6), op.hl_register_set_reference, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.a_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.b_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.c_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.d_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.e_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.h_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.l_register, 2),
         create_instruction("res", create_dynamic_byte_operand(7), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(0), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(1), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(2), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(3), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(4), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(5), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(6), op.hl_register_set_reference, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.a_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.b_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.c_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.d_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.e_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.h_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.l_register, 2),
         create_instruction("set", create_dynamic_byte_operand(7), op.hl_register_set_reference, 2)
      })
   end)
end)
